name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'qa')
    steps:
      - name: Docker test
        run: |
          docker images
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: furman9596/github_env
      - name: See tags and labels
        run: |
          echo "version: ${{ steps.meta.outputs.version }}"
          echo "---------------"
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "---------------"
          echo "labels: ${{ steps.meta.outputs.labels }}"
          echo "---------------"
          echo "json: ${{ steps.meta.outputs.json }}"
          echo "---------------"
          cat ${{ steps.meta.outputs.bake-file }}
  deploy-qa:
    if: contains(github.ref,'qa')
    runs-on: ubuntu-latest
    environment: qa
    needs: [ build-and-publish ]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Deploy to qa ECS
       uses: ./.github/actions/deploy-to-ecs
       with:
         cluster: qa
         version: v1.2.3
         aws-access-key: ${{ secrets.TEST_KEY }}
         aws-secret-access-key: ${{ secrets.TEST_SECRET_ACCESS_KEY }}
  tag-latest-with-version:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tag')
    steps:
      - name: Get current qa latest
        run: echo Pulling latest image
      - name: Get tag from github ref
        run: echo "THE_VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Tag current qa latest with tag
        run: echo Tagging latest qa image with ${{ env.THE_VERSION_TAG }}


