name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        run: |
          tag="the-tag"
          tag_to_pull="tag-to-pull"
          echo "::set-output name=tag::$tag"
          echo "::set-output name=tag-to-pull::$tag_to_pull"
      - run: |
          echo "tag: ${{ steps.get-tag.outputs.tag }}"
          echo "tag-to-pull: ${{ steps.get-tag.outputs.tag-to-pull }}"
# name: Deploy github_env app

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy-demo:
#    runs-on: ubuntu-latest
#    steps:
  
#       run: |
#         tag="the-tag"
#         tag_to_pull="tag-to-pull"
#         echo "::set-output name=tag::$tag"
#         echo "::set-output name=tag-to-pull::$tag_to_pull"
    -
