name: Deploy github_env to prod
on:
  workflow_dispatch:
    inputs:
      type:
        description: Version type to increment(major, minor, patch)
        required: false

jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - id: get-tag
        run: |
          git tag --sort=-v:refname | sed 10q
          echo "-----------------"
          echo "current-prod-tag $(git tag --sort=-v:refname | sed 1q)"
          echo "-----------------"
          echo "::set-output name=current-prod-tag::$(git tag --sort=-v:refname | sed 1q)"

