name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: run stuff
        run: |
          pip || echo "Pip not install"
          mysql || echo "mysql not installed"
          redis || echo "redis not installed"


