name: Deploy github_env app

on:
  push:
    branches:
      - qa

jobs:
  deploy-qa:
   runs-on: ubuntu-latest
   environment: qa
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Deploy to qa ECS
       uses: ./.github/actions/deploy-to-ecs
       with:
         cluster: qa
         version: v1.2.3
         aws-access-key: test-access-key-bruh
         aws-secret-access-key: test-secret-access-key-bruh
