name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run stuff
        uses: ./.github/actions/test
        with: 'v1.0.0'