name: Deploy github_env app

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
   runs-on: ubuntu-latest
   environment: demo
   steps:
     - name: Deploy to demo ECS
       run: |
         echo "Running docker container to deploy to ECS demo..."
         sleep 3
         echo "Deployed demo!!"
  deploy-prod:
    runs-on: ubuntu-latest
#    environment: prod
    needs: [deploy-demo]
    steps:
      - name: Deploy to prod ECS
        run: |
          echo "Running docker container to deploy to ECS prod..."
          sleep 3
          echo "Deployed prod"