name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate UUID
        id: generate-build-uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
      - name: Get output
        run: |
          echo "bruh ${{ steps.generate-build-uuid.outputs.uuid }}"
      - name: Adding an extra step
        run: |
          echo "Run extra step"