name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: furman9596/github_env:qa-latest
      - name: Save tag to file
        run: echo "$(git rev-parse --short HEAD)" > image-tag.txt
      - name: Cat image-tag.txt
        run: cat ./image-tag.txt
      - name: Cache qa tag
        uses: actions/cach@v2
        with:
          key: image-tag
          path: |
            ./image-tag.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [ build-and-publish ]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Deploy to qa ECS
       uses: ./.github/actions/deploy-to-ecs
       with:
         cluster: qa
         version: v1.2.3
         aws-access-key: ${{ secrets.TEST_KEY }}
         aws-secret-access-key: ${{ secrets.TEST_SECRET_ACCESS_KEY }}
  tag-latest-with-version:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tag')
    steps:
      - name: Get current qa latest
        run: echo Pulling latest image
      - name: Get tag from github ref
        run: echo "THE_VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Tag current qa latest with tag
        run: echo Tagging latest qa image with ${{ env.THE_VERSION_TAG }}


