name: Deploy github_env app

on:
  push:
    branches:
      - main
jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git tag -f $(git describe --tags)-staging
          git push --tags