name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Export env variables
        run: |
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILT_AT=$(date)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            furman9596/github_env:latest
          build-args: |
            GIT_SHA=${{ env.GIT_SHA }}
            BUILT_AT=${{ env.BUILT_AT }}
#      - name: Build and push image
#        run: |
#          docker build -t furman9596/github_env -t "furman9596/github_env:$(git rev-parse --short HEAD)" .
#          docker push --all-tags furman9596/github_env
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [ build-and-publish ]
#    steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2
#     - name: Deploy to qa ECS
#       uses: ./.github/actions/deploy-to-ecs
#       with:
#         cluster: qa
#         version: v1.2.3
#         aws-access-key: ${{ secrets.TEST_KEY }}
#         aws-secret-access-key: ${{ secrets.TEST_SECRET_ACCESS_KEY }}


