name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Export env variables
        run: |
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILT_AT=$(date)" >> $GITHUB_ENV
      - name: Docker images
        run: |
          docker images
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: |
            furman9596/github_env:scanned
          build-args: |
            GIT_SHA=${{ env.GIT_SHA }}
            BUILT_AT=${{ env.BUILT_AT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Scan image for security vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.2.1
        with:
          args: --cache-dir /var/lib/trivy --light --exit-code 1 --no-progress --ignore-unfixed --clear-cache furman9596/github_env:scanned
      - name: Push images
        run: |
          docker images
          docker push furman9596/github_env:scanned



