name: Deploy github_env app
# https://dille.name/blog/2018/09/20/how-to-tag-docker-images-without-pulling-them/

on:
  push:
    branches:
      - qa

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate UUID
        id: generate-uuid
        run: |
          echo "::set-output name=uuid::$(uuidgen)"
      - name: Get output
        run: |
          echo "bruh ${{ steps.generate-uuid.uuid }}"
#      - uses: actions/cache@v2
#        with:
#          path: build_uuid.txt
#          key: ${{ runner.os }}-build-uuid-${{ hashFiles('build_uuid.txt') }}
#      - name: generate uuid
#        run: |
#          uuidgen > build_uuid.txt
