name: Hotfix

on: workflow_dispatch

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git commit --allow-empty -m "Merging hotfix into main from '${{ github.ref_name }}'"
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: |
          echo "ref_name: ${{ github.ref_name }}"
          git checkout main
          git merge ${{ github.ref_name }}
          git push
