name: Hotfix

on: workflow_dispatch

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git status
          git config --local user.email "ferminsandoval950@hotmail.com"
          git config --local user.name "furman950"
          git commit --allow-empty -m "Merging hotfix into main from '${{ github.ref_name }}'"
          git checkout main
          git merge ${{ github.ref_name }}
          git push
