name: Manually rollback to version
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: Version to deploy
        required: true
jobs:
  rollback-github-env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.inputs.version-tag }}"