name: Exploring versioning
on:
  push:
    branches:
      - main
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.2
        id: generate-version
      - run: |
          echo "major ${{ steps.generate-version.outputs.major }}"
          echo "minor ${{ steps.generate-version.outputs.minor }}"
          echo "patch ${{ steps.generate-version.outputs.patch }}"
          echo "increment ${{ steps.generate-version.outputs.increment }}"
          echo "version ${{ steps.generate-version.outputs.version }}"
          echo "version_tag ${{ steps.generate-version.outputs.version_tag }}"
          echo "changed ${{ steps.generate-version.outputs.changed }}"
          git tag "${{ steps.generate-version.outputs.version }}+${{ steps.generate-version.outputs.increment }}"
          git push --tags