name: Exploring versioning
on:
  push:
    branches:
      - main
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.2
        id: generate-version
      - run: |
          echo "Version ${{ steps.generate-version.outputs.version }}"
          git tag ${{ steps.generate-version.outputs.version }}
          git push --tags