name: Exploring versioning
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to increment
        required: true
      type:
        description: Version type to increment(major, minor, patch)
        required: true
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/increment-semantic-version
        with:
          version: v1.2.3
          type: minor